# Generated by Django 3.1.14 on 2022-02-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20220217_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='element_type', to='pokemon_entities.PokemonElementType', verbose_name='Стихия'),
        ),
    ]
