# Generated by Django 3.1.14 on 2022-02-17 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20220217_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='elements', to='pokemon_entities.PokemonElementType', verbose_name='Стихия'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pokemon_entities.pokemon', verbose_name='Покемон'),
        ),
    ]
