# Generated by Django 3.1.14 on 2022-02-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20220217_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(related_name='advantages', to='pokemon_entities.PokemonElementType', verbose_name='Силен против'),
        ),
    ]
