# Generated by Django 3.1.14 on 2022-02-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20220217_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonelementtype',
            old_name='strong_against',
            new_name='advantages',
        ),
    ]
